// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngycuhvxrwrnngqhaxcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5neWN1aHZ4cndybm5ncWhheGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjEyMTYsImV4cCI6MjA3MzIzNzIxNn0.C5dWOKaT4XErpd4-b2LCTXfZpfXo0urD-5Urt0pYVcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});